name: Default template
description: The default template for all issues
body:
  - type: markdown
    attributes:
      value: |
        # Rules
  - type: markdown
    attributes:
      value: |
        **🚨🚨🚨Please read this section carefully and *COMPLETELY*.🚨🚨🚨 You may be blocked from this repository if you violate the rules.**
  - type: markdown
    attributes:
      value: |
        Picocrypt is a "finished" piece of software and is in a maintenance-only stage. This does not mean the software is old, outdated, or abandonware, but that the sole focus is on fixing bugs and ensuring the software continues to work smoothly as opposed to actively developing new features. As well, my time as the developer is very limited considering that Picocrypt brings me no monetary benefit and is entirely a gift of my time and skill to the community.
  - type: markdown
    attributes:
      value: |
        *Therefore, to save me time so that I can focus on the important things, please follow the guidelines below depending on your topic.*
  - type: markdown
    attributes:
      value: |
        ### Bug reports or security issues
  - type: markdown
    attributes:
      value: |
        These are important; make the issue with a short description, and then once the issue is created, add a comment with as many details as possible. Ping me (@HACKERALERT) in the comment so that I can get to it as soon as possible. Keep in mind that I define "bug" as something wrong with Picocrypt's code itself. If it's not Picocrypt's fault, it's not a bug.
  - type: markdown
    attributes:
      value: |
        ### Problems running/starting Picocrypt
  - type: markdown
    attributes:
      value: |
        Usually these issues are not directly caused by Picocrypt's code. If you're on Windows, see [here](https://github.com/Picocrypt/Picocrypt/issues/91). If you're on Linux, install some packages and try again (see [here](https://github.com/Picocrypt/Picocrypt/tree/main/src#1-prerequisites)). Picocrypt only targets Windows 11, Ubuntu 24/Debian 12, and macOS 15 or later, so *do not create an issue if your OS is older than those; that is your problem, not mine*. If none of the points above help, create the issue and in a separate comment, provide details about the environment you're running in (like OS, DE, etc.). **Do not ping me initially.** Let the issue sit for at least *5 days* to allow other users to potentially help you resolve the issue. If after 5 days, you haven't figured things out, then you may ping me (@HACKERALERT).
  - type: markdown
    attributes:
      value: |
        ### Picocrypt is crashing
  - type: markdown
    attributes:
      value: |
        This is almost always caused by input/output files being in locations where you don't have the correct read/write permissions. Try working within your user/home folder only and copy to/from other places to see if that resolves the crash. If not, run Picocrypt from the command line (e.g. `Picocrypt.exe` or `./Picocrypt`) so you can read the crash message. If you still can't fix the crash, create an issue and ping me (@HACKERALERT).
  - type: markdown
    attributes:
      value: |
        ### Antivirus problems
  - type: markdown
    attributes:
      value: |
        These are unpreventable; report them as false positives to your antivirus software provider and **do not create an issue about it**.
  - type: markdown
    attributes:
      value: |
        ### Support requests/usage questions
  - type: markdown
    attributes:
      value: |
        Create the issue and ask your question or support request in a separate comment. **Do not ping me initially.** Let the issue sit for at least *10 days* to give other users a chance to help you first. If after 10 days, you have not received any assistance, then you may ping me (@HACKERALERT).
  - type: markdown
    attributes:
      value: |
        ### Feature requests/suggestions
  - type: markdown
    attributes:
      value: |
        Picocrypt is mature software; I do not intend to add any new features. **Do not create these types of issues.**
  - type: markdown
    attributes:
      value: |
        ### Performance issues/improvements
  - type: markdown
    attributes:
      value: |
        Picocrypt prioritizes correctness and reliability over performance, so many parts of the code are written sequentially and don't use concurrency. This is intentional and need not be pointed out. Unless performance is absolutely atrocious to the point where it is indicative of a potential bug, **do not make issues about performance**.
  - type: markdown
    attributes:
      value: |
        ### Other issues/generic topics
  - type: markdown
    attributes:
      value: |
        You will have to use your best judgement here. Read the sections above to get an idea of what I expect to see and do what you think is best. Ideally, ping me only if sufficient time has passed for other users to assist/answer you, or it is best addressed by me directly. You must first look through existing issues or do a web search (AI can help!) before creating the issue. While I am allowing these generic issues to be made, if they become a hassle, I reserve the right to disallow them in the future.
  - type: checkboxes
    id: confirmation
    attributes:
      label: "Please confirm:"
      options:
        - label: "I have carefully read and agree to the rules outlined above"
          required: true
        - label: "I will provide as many helpful details as possible"
          required: true
        - label: "I acknowledge my issue may be ignored or closed without explanation"
          required: true
        - label: "I have looked through previous issues and related info already"
          required: true
        - label: "I will remember to close my issue when it is resolved"
          required: true
  - type: input
    id: summary
    attributes:
      label: "Describe the issue briefly in a few sentences:"
      description: "You can add more details in a separate comment after creating the issue."
    validations:
      required: true
